Repository apache/dolphinscheduler-sdk-python, pull requests merged in 2022-12, with the labels that each got.

#33 [impv] Do not warnings in dev version
  src/pydolphinscheduler/java_gateway.py
  tests/integration/test_java_gateway.py
Labels: improvement

#36 [fix] Resource upload and add document
  docs/source/concept.rst
  docs/source/howto/index.rst
  docs/source/howto/multi-resources.rst
  src/pydolphinscheduler/core/task.py
  src/pydolphinscheduler/core/workflow.py
  src/pydolphinscheduler/examples/multi_resources_example.py
  src/pydolphinscheduler/models/tenant.py
  tests/integration/test_resources.py
  tests/testing/constants.py
Labels: bug

#37 [chore] Fix ubuntu-latest can not setup python in github action
  .github/workflows/ci.yaml
Labels: chore

#39 [chore] Change website link
  .asf.yaml
Labels: chore

#41 [feat] Mark workflow timeout as type timedelta
  README.md
  UPDATING.md
  examples/yaml_define/MoreConfiguration.yaml
  src/pydolphinscheduler/constants.py
  src/pydolphinscheduler/core/task.py
  src/pydolphinscheduler/utils/date.py
  tests/core/test_task.py
  tests/utils/test_date.py
Labels: enhancement, incompatible

#42 [chore] Change workflow instance name from pd
  docs/source/concept.rst
  src/pydolphinscheduler/core/workflow.py
  src/pydolphinscheduler/core/yaml_workflow.py
  src/pydolphinscheduler/examples/bulk_create_example.py
  src/pydolphinscheduler/examples/multi_resources_example.py
  src/pydolphinscheduler/examples/task_condition_example.py
  src/pydolphinscheduler/examples/task_datax_example.py
  src/pydolphinscheduler/examples/task_dependent_example.py
  src/pydolphinscheduler/examples/task_dvc_example.py
  src/pydolphinscheduler/examples/task_flink_example.py
  src/pydolphinscheduler/examples/task_kubernetes_example.py
  src/pydolphinscheduler/examples/task_map_reduce_example.py
  src/pydolphinscheduler/examples/task_mlflow_example.py
  src/pydolphinscheduler/examples/task_openmldb_example.py
  src/pydolphinscheduler/examples/task_pytorch_example.py
  src/pydolphinscheduler/examples/task_sagemaker_example.py
  src/pydolphinscheduler/examples/task_spark_example.py
  src/pydolphinscheduler/examples/task_switch_example.py
  src/pydolphinscheduler/examples/tutorial.py
  src/pydolphinscheduler/examples/tutorial_decorator.py
  tests/core/test_workflow.py
  tests/integration/test_process_definition.py
  tests/tasks/test_condition.py
  tests/tasks/test_func_wrap.py
  tests/tasks/test_switch.py
Labels: chore

#43 [impv] Add option param for workflow and task
  src/pydolphinscheduler/core/task.py
  src/pydolphinscheduler/core/workflow.py
  tests/core/test_task.py
Labels: improvement

#46 [Test] Optimize the test cases in the task plugin
  tests/tasks/test_condition.py
  tests/tasks/test_datax.py
  tests/tasks/test_dependent.py
  tests/tasks/test_dvc.py
  tests/tasks/test_flink.py
  tests/tasks/test_http.py
  tests/tasks/test_kubernetes.py
  tests/tasks/test_map_reduce.py
  tests/tasks/test_mlflow.py
  tests/tasks/test_openmldb.py
  tests/tasks/test_procedure.py
  tests/tasks/test_python.py
  tests/tasks/test_pytorch.py
  tests/tasks/test_sagemaker.py
  tests/tasks/test_shell.py
  tests/tasks/test_spark.py
  tests/tasks/test_sql.py
  tests/tasks/test_sub_workflow.py
  tests/tasks/test_switch.py
Labels: improvement

#44 [feat] Add changelog to our documentation
  docs/source/changelog.rst
  docs/source/conf.py
  docs/source/index.rst
  setup.py
Labels: documentation

#47 [feat] Version check for dolphinscheduler main package
  setup.py
  src/pydolphinscheduler/constants.py
  src/pydolphinscheduler/java_gateway.py
  src/pydolphinscheduler/utils/versions.py
  src/pydolphinscheduler/version_ext
  tests/utils/test_versions.py
Labels: enhancement

#50 [Feat] Add task caching mechanism to improve the running speed of repetitive tasks
  examples/yaml_define/MoreConfiguration.yaml
  src/pydolphinscheduler/constants.py
  src/pydolphinscheduler/core/task.py
  tests/core/test_engine.py
  tests/core/test_task.py
Labels: enhancement, dep-main-repo

#55 fix: flake8 upgrade syntax error and changelog token
  .flake8
  docs/source/conf.py
Labels: bug

#54 [impv] Remove tenant define is workflow
  UPDATING.md
  docs/source/concept.rst
  docs/source/config.rst
  examples/yaml_define/tutorial.yaml
  src/pydolphinscheduler/configuration.py
  src/pydolphinscheduler/core/default_config.yaml
  src/pydolphinscheduler/core/workflow.py
  src/pydolphinscheduler/default_config.yaml
  src/pydolphinscheduler/examples/bulk_create_example.py
  src/pydolphinscheduler/examples/multi_resources_example.py
  src/pydolphinscheduler/examples/task_condition_example.py
  src/pydolphinscheduler/examples/task_datax_example.py
  src/pydolphinscheduler/examples/task_dependent_example.py
  src/pydolphinscheduler/examples/task_dvc_example.py
  src/pydolphinscheduler/examples/task_flink_example.py
  src/pydolphinscheduler/examples/task_kubernetes_example.py
  src/pydolphinscheduler/examples/task_map_reduce_example.py
  src/pydolphinscheduler/examples/task_mlflow_example.py
  src/pydolphinscheduler/examples/task_openmldb_example.py
  src/pydolphinscheduler/examples/task_pytorch_example.py
  src/pydolphinscheduler/examples/task_sagemaker_example.py
  src/pydolphinscheduler/examples/task_spark_example.py
  src/pydolphinscheduler/examples/task_switch_example.py
  src/pydolphinscheduler/examples/tutorial.py
  src/pydolphinscheduler/examples/tutorial_decorator.py
  src/pydolphinscheduler/examples/tutorial_resource_plugin.py
  src/pydolphinscheduler/java_gateway.py
  src/pydolphinscheduler/models/tenant.py
  src/pydolphinscheduler/models/user.py
  tests/core/test_workflow.py
  tests/test_configuration.py
  tests/utils/test_yaml_parser.py
Labels: improvement, dep-main-repo, incompatible

#56 feat: Add post command to tox do some clean
  docs/source/conf.py
  tox.ini
Labels: bug

#53 [improve] More pythonic way for parameter local_params in class task
  .gitignore
  docs/source/concept.rst
  examples/yaml_define/MoreConfiguration.yaml
  src/pydolphinscheduler/core/parameter.py
  src/pydolphinscheduler/core/task.py
  src/pydolphinscheduler/core/yaml_workflow.py
  src/pydolphinscheduler/examples/local_parameter_example.py
  tests/core/test_local_parameter.py
  tests/core/test_task.py
  tests/core/test_yaml_workflow.py
Labels: enhancement

#52 [doc] Release document add
  .gitignore
  RELEASE.md
Labels: documentation

#62 fix: sql task pre post stm typing and add example
  docs/source/tasks/sql.rst
  src/pydolphinscheduler/examples/ext/example.sql
  src/pydolphinscheduler/examples/task_sql_example.py
  src/pydolphinscheduler/tasks/sql.py
  tests/tasks/test_sql.py
  tests/testing/constants.py
Labels: bug

#63 feat: Add stmdency handle @task decorate statement dependency
  docs/source/tasks/func_wrap.rst
  setup.py
  src/pydolphinscheduler/examples/tutorial_decorator.py
  src/pydolphinscheduler/tasks/func_wrap.py
  src/pydolphinscheduler/tasks/python.py
  tests/tasks/test_func_wrap.py
Labels: enhancement

#64 feat: Use setup.cfg for dist package
  .github/workflows/ci.yaml
  RELEASE.md
  docs/source/conf.py
  setup.cfg
  setup.py
  src/pydolphinscheduler/__init__.py
Labels: chore
