Repository apache/dolphinscheduler-sdk-python, pull requests merged in 2023-10, with the labels that each got.

#111 chore: Remove review required
  .asf.yaml
  CONTRIBUTING.md
Labels: chore

#112 doc: Add how to config alert
  docs/source/concept.rst
Labels: documentation

#114 feat: Add task group to task class
  docs/source/concept.rst
  src/pydolphinscheduler/core/task.py
  tests/core/test_engine.py
  tests/core/test_task.py
Labels: enhancement

#117 doc: Add support version and NIT doc
  .gitignore
  RELEASE.md
  docs/source/index.rst
Labels: documentation

#113 feat: Support python 3.12
  .github/workflows/ci.yaml
  CONTRIBUTING.md
  setup.cfg
  src/pydolphinscheduler/utils/versions.py
  tests/utils/test_versions.py
Labels: enhancement

#110 Add WorkerResourceMixin, enabling customers to set CPU quotas and max memory via the Python API
  docs/source/concept.rst
  docs/source/start.rst
  docs/source/tasks/datax.rst
  docs/source/tasks/python.rst
  docs/source/tasks/pytorch.rst
  docs/source/tasks/shell.rst
  docs/source/tutorial.rst
  setup.cfg
  src/pydolphinscheduler/core/mixin.py
  src/pydolphinscheduler/core/parameter.py
  src/pydolphinscheduler/core/task.py
  src/pydolphinscheduler/examples/task_datax_example.py
  src/pydolphinscheduler/examples/task_python_example.py
  src/pydolphinscheduler/examples/task_pytorch_example.py
  src/pydolphinscheduler/examples/tutorial.py
  src/pydolphinscheduler/models/base.py
  src/pydolphinscheduler/tasks/datax.py
  src/pydolphinscheduler/tasks/python.py
  src/pydolphinscheduler/tasks/pytorch.py
  src/pydolphinscheduler/tasks/shell.py
  tests/tasks/test_datax.py
  tests/tasks/test_python.py
  tests/tasks/test_pytorch.py
  tests/tasks/test_shell.py
  tests/testing/constants.py
Labels: enhancement
