Repository apache/dolphinscheduler-sdk-python, pull requests merged in 2023-12, with the labels that each got.

#124 fix: CI deadlink error
  .dlc.json
Labels: documentation

#123 [impv] Change the parameter types of task and workflow to Union[timedelta, int]
  src/pydolphinscheduler/core/task.py
  src/pydolphinscheduler/core/workflow.py
  tests/core/test_task.py
  tests/core/test_workflow.py
Labels: improvement

#125 feat: introduce ruff for linter
  .pre-commit-config.yaml
  .ruff.toml
  setup.cfg
  src/pydolphinscheduler/configuration.py
  src/pydolphinscheduler/core/mixin.py
  src/pydolphinscheduler/core/resource_plugin.py
  src/pydolphinscheduler/core/task.py
  src/pydolphinscheduler/core/yaml_workflow.py
  src/pydolphinscheduler/models/meta.py
  src/pydolphinscheduler/resources_plugin/base/bucket.py
  src/pydolphinscheduler/resources_plugin/base/git.py
  src/pydolphinscheduler/resources_plugin/gitlab.py
  src/pydolphinscheduler/resources_plugin/local.py
  src/pydolphinscheduler/utils/versions.py
  tests/core/test_yaml_workflow.py
  tests/testing/file.py
  tests/utils/test_default_config_yaml.py
  tests/utils/test_yaml_parser.py
Labels: chore

#126 chore: Drop support of py36 and py37
  .github/workflows/ci.yaml
  RELEASE.md
  UPDATING.md
  setup.cfg
Labels: chore

#128 feat: Apply PEP-563 for codebase
  .ruff.toml
  setup.py
  src/pydolphinscheduler/core/engine.py
  src/pydolphinscheduler/core/resource.py
  src/pydolphinscheduler/core/task.py
  src/pydolphinscheduler/core/workflow.py
  src/pydolphinscheduler/core/yaml_workflow.py
  src/pydolphinscheduler/java_gateway.py
  src/pydolphinscheduler/models/base.py
  src/pydolphinscheduler/models/base_side.py
  src/pydolphinscheduler/models/datasource.py
  src/pydolphinscheduler/models/meta.py
  src/pydolphinscheduler/models/project.py
  src/pydolphinscheduler/models/queue.py
  src/pydolphinscheduler/models/tenant.py
  src/pydolphinscheduler/models/user.py
  src/pydolphinscheduler/models/worker_group.py
  src/pydolphinscheduler/resources_plugin/base/bucket.py
  src/pydolphinscheduler/resources_plugin/base/git.py
  src/pydolphinscheduler/resources_plugin/github.py
  src/pydolphinscheduler/resources_plugin/gitlab.py
  src/pydolphinscheduler/resources_plugin/oss.py
  src/pydolphinscheduler/resources_plugin/s3.py
  src/pydolphinscheduler/tasks/condition.py
  src/pydolphinscheduler/tasks/datax.py
  src/pydolphinscheduler/tasks/dependent.py
  src/pydolphinscheduler/tasks/dvc.py
  src/pydolphinscheduler/tasks/flink.py
  src/pydolphinscheduler/tasks/http.py
  src/pydolphinscheduler/tasks/map_reduce.py
  src/pydolphinscheduler/tasks/mlflow.py
  src/pydolphinscheduler/tasks/procedure.py
  src/pydolphinscheduler/tasks/python.py
  src/pydolphinscheduler/tasks/pytorch.py
  src/pydolphinscheduler/tasks/spark.py
  src/pydolphinscheduler/tasks/sql.py
  src/pydolphinscheduler/tasks/sub_workflow.py
  src/pydolphinscheduler/tasks/switch.py
  src/pydolphinscheduler/utils/file.py
  src/pydolphinscheduler/utils/yaml_parser.py
  tests/core/test_task.py
  tests/core/test_workflow.py
  tests/integration/test_process_definition.py
  tests/tasks/test_condition.py
  tests/tasks/test_dependent.py
  tests/tasks/test_switch.py
  tests/testing/docker_wrapper.py
  tests/testing/file.py
  tests/testing/path.py
  tests/utils/test_date.py
  tests/utils/test_yaml_parser.py
Labels: chore

#129 fix: Integration test error
  tests/integration/test_user.py
Labels: bug
